function isDigit(eve) {eve.value = eve.value.replace(/[^\d]/g, '')}function formChaxun(t, l) {var A = $(t).val(),B = $(l).val();if (A == 1 && B >= 20 || A == 2 && B <= 18) {alert = "您的星座是--【水瓶座】";}if (A == 2 && B >= 19 && B <= 29 || A == 3 && B <= 20) {alert("您的星座是--【双鱼座】");}if (A == 2 && B > 29) {alert("2月最多29天！");}if (A == 3 && B >= 21 || A == 4 && B <= 19) {alert("您的星座是--【白羊座】");}if (A == 4 && B >= 20 && B <= 30 || A == 5 && B <= 20) {alert("您的星座是--【金牛座】");}if (A == 4 && B > 30) {alert("4月只有30天！");}if (A == 5 && B >= 21 || A == 6 && B <= 21) {alert("您的星座是--【双子座】");}if (A == 6 && B >= 22 && B <= 30 || A == 7 && B <= 22) {alert("您的星座是--【巨蟹座】");}if (A == 6 && B > 30) {alert("6月只有30天！");}if (A == 7 && B >= 23 || A == 8 && B <= 22) {alert("您的星座是--【狮子座】");}if (A == 8 && B >= 23 || A == 9 && B <= 22) {alert("您的星座是--【处女座】");}if (A == 9 && B >= 23 && B <= 30 || A == 10 && B <= 22) {alert("您的星座是--【天秤座】");}if (A == 9 && B > 30) {alert("9月只有30天！");}if (A == 10 && B >= 23 || A == 11 && B <= 21) {alert("您的星座是--【天蝎座】");}if (A == 11 && B >= 22 && B <= 30 || A == 12 && B <= 21) {alert("您的星座是--【射手座】");}if (A == 11 && B > 30) {alert("11月只有30天！");}if (A == 12 && B >= 22 || A == 1 && B <= 19) {alert("您的星座是--【摩羯座】");}return false}
function formFortune(u, f, t, l) {var A = $(t).val(),B = $(l).val(),UR = $(u).val();$(f).attr("action", UR + A + B + ".php");$(f).attr("method", "get");return true}
function formAstro(u, f, t) {var A = $(t).val(),UR = $(u).val();$(f).attr("action", UR + A + "/");$(f).attr("method", "get");return true}function formShenrimm(u, f, t, l) {var A = $(t).val(),B = $(l).val(),UR = $(u).val();if (A == 2 && B > 29 || A == 4 && B > 30 || A == 6 && B > 30 || A == 9 && B > 30 || A == 11 && B > 30) {alert("今年暂时没有这一天,请重新输入！");return false;} else {$(f).attr("action", UR + A + "-" + B + ".html");$(f).attr("method", "get");return true}}
function formShenrihy(u, f, t, l) {var A = $(t).val(),B = $(l).val(),UR = $(u).val();if (A == 2 && B > 29 || A == 4 && B > 30 || A == 6 && B > 30 || A == 9 && B > 30 || A == 11 && B > 30) {alert("今年暂时没有这一天,请重新输入！");return false;} else {$(f).attr("action", UR + A + "-" + B + ".html");$(f).attr("method", "get");return true}}
function formSupeixz(u, f, t, l) {var A = $(t).val(),B = $(l).val(),UR = $(u).val();$(f).attr("action", UR + A + B + ".html");$(f).attr("method", "get");return true}
function formSupeisx(u, f, t, l) {var A = $(t).val(),B = $(l).val(),UR = $(u).val();$(f).attr("action", UR + A + B + ".html");$(f).attr("method", "get");return true}
function formSupeixx(u, f, t, l) {var A = $(t).val(),B = $(l).val(),C = A + B,UR = $(u).val();if (C == "B-A") {C = "A-B"}if (C == "AB-A") {C = "A-AB"}if (C == "O-A") {C = "A-O"}if (C == "AB-B") {C = "B-AB"}if (C == "O-B") {C = "B-O"}if (C == "O-AB") {C = "AB-O"}$(f).attr("action", UR + C + ".html");$(f).attr("method", "get");return true}
function formXinggexz(u, f, t, l) {var A = $(t).val(),B = $(l).val(),UR = $(u).val();$(f).attr("action", UR + A + B + ".html");$(f).attr("method", "get");return true}
function formXinggexx(u, f, t, l) {var A = $(t).val(),B = $(l).val(),UR = $(u).val();$(f).attr("action", UR + A + B + ".html");$(f).attr("method", "get");return true}
function formXinggesx(u, f, t, l) {var A = $(t).val(),B = $(l).val(),UR = $(u).val();$(f).attr("action", UR + A + "" + B + ".html");$(f).attr("method", "get");return true}//function formHuangdao(u, f, y, m, d){var A = $(y).val(),B = $(m).val(),C = $(d).val(),E = A % 4,UR = $(u).val();if (E > 0){if (B == 2 && C > 28 || B == 4 && C > 30 || B == 6 && C > 30 || B == 9 && C > 30 || B == 11 && C > 30 ){alert("今年暂时没有这一天,请重新输入！");return false;}else {$(f).attr("action", UR + A + "-" + B + "-" + C + ".html");$(f).attr("method", "get");return true}}else {if (B == 2 && C > 29 || B == 4 && C > 30 || B == 6 && C > 30 || B == 9 && C > 30 || B == 11 && C > 30 ){alert("今年暂时没有这一天,请重新输入！");return false;}else {$(f).attr("action", UR + A + "-" + B + "-" + C + ".html");$(f).attr("method", "get");return true}}}
